// Hard-coded data for simplicity, but using an API would be more appropriate in production.
const data = [
  {
    id: 0,
    title: 'The Shawshank Redemption',
    format: 'movie',
    year: '1994',
    genres: ['Drama'],
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    pos: 'top',
  },
  { 
    id: 1,
    title: 'The Usual Suspects',
    format: 'movie',
    year: '2015-2019',
    genres: ['Crime', 'Drama', 'Mystery'],
    description: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
    pos: 'top',
  },
  { 
    id: 2,
    title: "The Hitchhiker's Guide to the Galaxy",
    format: 'movie',
    year: '2005',
    genres: ['Adventure', 'Comedy', 'Sci-Fi'],
    description: "Mere seconds before the Earth is to be demolished by an alien construction crew, journeyman Arthur Dent is swept off the planet by his friend Ford Prefect, a researcher penning a new edition of 'The Hitchhiker's Guide to the Galaxy.'",
  },
  {
    id: 3,
    title: 'No Country For Old Men',
    format: 'movie',
    year: '2007',
    genres: ['Crime', 'Drama', 'Thriller'],
    description: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
  },
  {
    id: 4,
    title: 'Breaking Bad',
    format: 'series',
    year: '2008-2013',
    genres: ['Crime', 'Drama', 'Thriller'],
    description: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
    pos: 'top',
  },
  {
    id: 5,
    title: 'Mr. Robot',
    format: 'series',
    year: '2015-2019',
    genres: ['Crime', 'Drama', 'Thriller'],
    description: "Elliot, a brilliant but highly unstable young cyber-security engineer and vigilante hacker, becomes a key figure in a complex game of global dominance when he and his shadowy allies try to take down the corrupt corporation he works for.",
  },
  {
    id: 6,
    title: 'What We Do in the Shadows',
    format: 'series',
    year: '2019-',
    genres: ['Comedy', 'Fantasy', 'Horror'],
    description: "A look into the daily (or rather, nightly) lives of four vampires, who've lived together for over 100 years, on Staten Island.",
  },
  {
    id: 7,
    title: 'The Office',
    format: 'series',
    year: '2005-2013',
    genres: ['Comedy'],
    description: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
  },
  {
    id: 8,
    title: 'The Shining',
    format: 'book',
    year: '1977',
    genres: ['Horror', 'Fiction', 'Thriller'],
    description: "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old.",
  },
  {
    id: 9,
    title: 'Fight Club',
    format: 'book',
    year: '1996',
    genres: ['Fiction', 'Classics', 'Contemporary'],
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
  },
  {
    id: 10,
    title: "The Hitchhiker's Guide to the Galaxy",
    format: 'book',
    year: '1979',
    genres: ['Sci-Fi', 'Fiction', 'Humor'],
    description: "Mere seconds before the Earth is to be demolished by an alien construction crew, journeyman Arthur Dent is swept off the planet by his friend Ford Prefect, a researcher penning a new edition of 'The Hitchhiker's Guide to the Galaxy.'",
    pos: 'bottom',
  },
  {
    id: 11,
    title: 'Guards! Guards!',
    format: 'book',
    year: '1989',
    genres: ['Fantasy', 'Fiction', 'Humor'],
    description: "The city of Ankh-Morpork no longer has a king and is now ruled by a corrupt Patrician. A secret society calls a dragon with the understanding that whoever kills it will be named King and bring a new rule to the kingdom. Things go wrong when the dragon is crowned King of the city and the four members of the Night Watch Guard must keep the new king from eating the citizens.",
    pos: 'top',
  },
  {
    id: 12,
    title: 'The Princess Bride',
    format: 'book',
    year: '1973',
    genres: ['Fantasy', 'Fiction', 'Humor'],
    description: "William Goldman's beloved story of Buttercup, Westley, and their fellow adventurers.This tale of true love, high adventure, pirates, princesses, giants, miracles, fencing, and a frightening assortment of wild beasts was unforgettably depicted in the 1987 film directed by Rob Reiner and starring Fred Savage, Robin Wright, and others. But, rich in character and satire, the novel boasts even more layers of ingenious storytelling. Set in 1941 and framed cleverly as an “abridged” retelling of a centuries-old tale set in the fabled country of Florin, home to “Beasts of all natures and descriptions. Pain. Death. Brave men. Coward men. Strongest men. Chases. Escapes. Lies. Truths. Passions.”",
    pos: 'top',
  },
  {
    id: 13,
    title: 'The Princess Bride',
    format: 'movie',
    year: '1987',
    genres: ['Fantasy', 'Adventure', 'Comedy'],
    description: "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner and starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest. Adapted by William Goldman from his 1973 novel of the same name, it tells the story of a farmhand named Westley, accompanied by companions befriended along the way, who must rescue his true love Princess Buttercup from the odious Prince Humperdinck. The film preserves the novel's metafictional narrative style by presenting the story as a book being read by a grandfather to his sick grandson.",
    pos: 'top',
  },
  {
    id: 14,
    title: 'Better Call Saul',
    format: 'series',
    year: '2015',
    genres: ['Crime', 'Drama'],
    description: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.",
    pos: 'top',
  }
]
export default data